#Configuration file used when running from docker compose.

server:
  port: 8000
  
management:
  endpoints:
    enabled-by-default: false #Disable actuator endpoints  

spring:
  data:
    mongodb:
      uri: mongodb://database:27017/prices
